name: 'MediaWiki Deploment'
on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch: 

permissions:
  contents: read

jobs:
  terraform:
    name: 'Infrastructure as Code'
    runs-on: ubuntu-latest
    #environment: dev
    env: 
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Login to Azure Subscription
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.DEV_SPN }}
   
    # Install Terraform to the GitHub Actions runner
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Export 
    - name: Acees Key of Bucket to Initialize remote backend
      run: |
        ACCOUNT_KEY=$(az storage account keys list --resource-group ${{ secrets.STG_RG_NAME }} --account-name ${{ secrets.STG_ACC_NAME }} --query '[0].value' -o tsv)
        export ARM_ACCESS_KEY=$ACCOUNT_KEY

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: |
        cd infrastructure
        terraform init       

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: |
        cd infrastructure
        terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: |
        cd infrastructure
        terraform plan -out=tfplan

    # Build or change infrastructure according to Terraform configuration files
    - name: Terraform Apply
      run: |
        cd infrastructure
        terraform apply -auto-approve tfplan
    
    # Logout from Azure Subscription
    - name: logout
      run: >
        az logout
  
  deploy-app:
    runs-on: ubuntu-latest
    needs: terraform
    env: 
      MEDIAWIKI_SUBSCRIPTION: ${{ secrets.SUBSCRIPTION_ID }}
      RESOURCE_GROUP: ${{ secrets.AKS_RG }}
      K8S_CLUSTERNAME: ${{ secrets.CLUSTERNAME }}
      MEDIAWIKI_NAMESPACE: "wiki"
    
    defaults:
      run:
        shell: bash
    steps:
        # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEV_SPN }}

      - name: Deploy Application
        run: |
         cd deploy
         chmod 755 deploy.sh
         ./deploy.sh
      
 
